on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |
          yarn install --frozen-lockfile
      - name: Quality
        run: |
          yarn quality
      - name: Run Release
        run: |
          yarn npx -p @qiwi/semrel-toolkit multi-semrel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
